name: Publish

on:
  push:
    tags:
      - 'v*.*.**'

jobs:
  publish_nuget_package:
    name: Publish Nuget Package
    
    runs-on: ubuntu-latest
    
    steps: 
        - uses: actions/checkout@v4
        
        - name: Set Version
          run: |
            VERSION=${ github.ref_name#v }
            sed -i -e 's/{{Version}}/${VERSION}/' ./src/MmcSerializer.csproj
        
        - name: Pack
          run: |
            dotnet pack ./src/MmcSerializer.csproj -c Release -o .output
        
        - name: Publish
          env: 
            API_KEY: ${{ secrets.NUGET_API_KEY }}
          run: |
            dotnet nuget push .output/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json

  publish_github_release:
    name: Punlish Github Release

    runs-on: ubuntu-latest

    needs: publish_nuget_package
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Published NuGet package for version ${{ github.ref_name }}.
          files: |
            ./artifacts/*.nupkg
    
    